(() => {
  "use strict";
  const articles = window.SPENSUS_ARTICLES || [];
  const state = { category: "Semua", query: "", active: null };
  const savedKey = "spensus-saved-articles-v37";
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const esc = (v) => String(v ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);
  const slug = (v) => String(v).normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
  function saved(){ try { const x=JSON.parse(localStorage.getItem(savedKey)||"[]"); return Array.isArray(x)?x:[]; } catch { return []; } }
  function isSaved(id){ return saved().includes(id); }
  function toggleSaved(id){ let list=saved(); list=list.includes(id)?list.filter(x=>x!==id):[id,...list]; localStorage.setItem(savedKey,JSON.stringify(list)); renderGrid(); if(state.active?.id===id) updateReaderButtons(); }
  const categories=["Semua",...new Set(articles.map(a=>a.category))];
  function filtered(){ const q=state.query.toLocaleLowerCase("id"); return articles.filter(a=>(state.category==="Semua"||a.category===state.category)&&(!q||`${a.title} ${a.excerpt} ${a.category}`.toLocaleLowerCase("id").includes(q))); }
  function renderChips(){ $("#article-chips").innerHTML=categories.map(c=>`<button type="button" data-category="${esc(c)}" class="${c===state.category?'is-active':''}">${esc(c)}</button>`).join(""); }
  function card(a,index){ return `<article class="article-card-v37" style="--tone:${(index%6)+1}"><div class="article-card-art-v37"><span>${esc(a.icon)}</span><b>${esc(a.category)}</b><i>${esc(a.read)}</i></div><div class="article-card-body-v37"><span>ARTIKEL PILIHAN</span><h2>${esc(a.title)}</h2><p>${esc(a.excerpt)}</p><div><button type="button" data-open-article="${esc(a.id)}">Baca utuh <b>→</b></button><button type="button" class="save-mini-v37 ${isSaved(a.id)?'is-saved':''}" data-save-article="${esc(a.id)}" aria-label="Simpan artikel">${isSaved(a.id)?'★':'☆'}</button></div></div></article>`; }
  function renderGrid(){ const list=filtered(); $("#article-count").textContent=`${list.length} artikel tersedia luring`; $("#article-grid").innerHTML=list.length?list.map(card).join(""):`<div class="article-empty-v37"><span>⌕</span><h2>Artikel belum ditemukan</h2><p>Ubah kategori atau kata pencarian.</p></div>`; }
  function articleHtml(a){ return `<article class="article-reader-content-v37" id="article-printable"><header><span>${esc(a.category)} • ${esc(a.read)}</span><h1>${esc(a.title)}</h1><p>${esc(a.excerpt)}</p></header><div class="article-lead-v37"><b>Inti bacaan</b><p>Artikel ini disusun secara orisinal untuk PAIBP SMART SMP dengan bahasa yang mudah dibaca, tidak menyalin isi sumber, dan tetap mengarahkan pembaca memeriksa rujukan tepercaya.</p></div>${a.sections.map((s,i)=>`<section><h2><span>${String(i+1).padStart(2,'0')}</span>${esc(s[0])}</h2><p>${esc(s[1])}</p></section>`).join("")}<section class="article-reflection-v37"><h2>Refleksi dan tindakan</h2><ol><li>Gagasan apa yang paling relevan dengan keadaanmu saat ini?</li><li>Kebiasaan kecil apa yang dapat dimulai dalam tujuh hari?</li><li>Siapa yang dapat diajak bekerja sama agar perubahan bertahan?</li></ol></section><section class="article-sources-v37"><h2>Rujukan untuk pemeriksaan lebih lanjut</h2><div>${a.sources.map(s=>`<a href="${esc(s[1])}" target="_blank" rel="noopener"><b>${esc(s[0])}</b><span>Buka sumber tepercaya ↗</span></a>`).join("")}</div></section><footer class="document-promo-v37"><b>PAIBP SMART SMP</b><span>Belajar • Paham • Berakhlak</span><small>https://paibpsmart.github.io/</small></footer></article>`; }
  function openArticle(id){ const a=articles.find(x=>x.id===id); if(!a)return; state.active=a; $("#article-library").hidden=true; $("#article-reader").hidden=false; $("#article-reader-body").innerHTML=articleHtml(a); updateReaderButtons(); history.replaceState(null,"",`artikel-islam.html?id=${encodeURIComponent(id)}`); scrollTo({top:0,behavior:"smooth"}); }
  function closeArticle(){ state.active=null; $("#article-reader").hidden=true; $("#article-library").hidden=false; history.replaceState(null,"","artikel-islam.html"); }
  function updateReaderButtons(){ const btn=$("#article-save-current"); if(btn&&state.active){ const yes=isSaved(state.active.id); btn.textContent=yes?'★ Tersimpan':'☆ Simpan'; btn.classList.toggle('is-saved',yes); } }
  function downloadDocx(){ if(!state.active||!window.PAIBP_DOCX)return; const blob=window.PAIBP_DOCX.createDocument({title:state.active.title,blocks:window.PAIBP_DOCX.blocksFromElement($("#article-printable"))}); const u=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=u;a.download=`artikel-${slug(state.active.title)}-paibp-smart.docx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1200); }
  async function share(){ if(!state.active)return; const data={title:state.active.title,text:`${state.active.title} — PAIBP SMART SMP`,url:location.href}; try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.text}\n${data.url}`);alert('Tautan artikel disalin.');}}catch(e){} }
  $("#article-chips").addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;state.category=b.dataset.category;renderChips();renderGrid();});
  $("#article-search").addEventListener('input',e=>{state.query=e.target.value;renderGrid();});
  $("#article-grid").addEventListener('click',e=>{const o=e.target.closest('[data-open-article]');if(o)openArticle(o.dataset.openArticle);const s=e.target.closest('[data-save-article]');if(s)toggleSaved(s.dataset.saveArticle);});
  $("#article-back").addEventListener('click',closeArticle); $("#article-save-current").addEventListener('click',()=>state.active&&toggleSaved(state.active.id)); $("#article-share").addEventListener('click',share); $("#article-docx").addEventListener('click',downloadDocx); $("#article-print").addEventListener('click',()=>window.print());
  renderChips();renderGrid(); const initial=new URLSearchParams(location.search).get('id'); if(initial)openArticle(initial);
})();