const CACHE_NAME="paibp-smart-v158-news-archive-exact";
const CORE=[
  "./","./index.html","./logo-spensus.png","./styles.css?v=37","./v37-final.css?v=37",
  "./app-config.js?v=85","./stable-v72.css?v=86","./mobile-fix-v70.css?v=86",
  "./visual-v86.css?v=86","./icon-v86.css?v=86","./ui-final-v105.css?v=109",
  "./ui-final-v105.js?v=109","./icon-art-v85.js?v=157","./home-news-v102.js?v=153","./news-ui-fast-v149.js?v=152","./share-ready-v152.js?v=152"
];
self.addEventListener("install",event=>{self.skipWaiting();event.waitUntil(caches.open(CACHE_NAME).then(cache=>Promise.allSettled(CORE.map(url=>cache.add(url)))))});
self.addEventListener("activate",event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key!==CACHE_NAME&&!key.startsWith("paibp-quran-kemenag-")).map(key=>caches.delete(key)));await self.clients.claim()})())});
async function fetchWithTimeout(request,ms){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),ms);try{return await fetch(request,{cache:"no-store",signal:ctl.signal})}finally{clearTimeout(timer)}}
async function networkFirst(request,ms=700){const cache=await caches.open(CACHE_NAME);try{const response=await fetchWithTimeout(request,ms);if(response&&response.ok)cache.put(request,response.clone());return response}catch{return await cache.match(request)||await cache.match(request,{ignoreSearch:true})||fetch(request)}}
async function staleWhileRevalidate(event,request){const cache=await caches.open(CACHE_NAME);const hit=await cache.match(request)||await cache.match(request,{ignoreSearch:true});const update=fetch(request,{cache:"no-store"}).then(response=>{if(response&&response.ok)cache.put(request,response.clone());return response}).catch(()=>null);if(event&&hit)event.waitUntil(update);return hit||await update||Response.error()}
async function cacheFirst(request){const cache=await caches.open(CACHE_NAME);const hit=await cache.match(request)||await cache.match(request,{ignoreSearch:true});if(hit)return hit;try{const response=await fetch(request,{cache:"no-store"});if(response&&response.ok)cache.put(request,response.clone());return response}catch{return Response.error()}}
async function navigationInstant(event,request){const cache=await caches.open(CACHE_NAME);const hit=await cache.match(request)||await cache.match(request,{ignoreSearch:true})||await cache.match("./index.html");if(hit){event.waitUntil(fetch(request,{cache:"no-store"}).then(response=>{if(response&&response.ok)return cache.put(request,response.clone())}).catch(()=>null));return hit}const fresh=await fetch(request,{cache:"no-store"});if(fresh&&fresh.ok)cache.put(request,fresh.clone());return fresh}
async function newsRuntime(request){const response=await fetchWithTimeout(request,1200);if(!response||!response.ok)return response;const source=await response.text();const patch=`\n;(()=>{const css=document.createElement("style");css.id="spensus-year-sidebar-exact-v158";css.textContent=\`#spensus-news-v102 .ig-side .ig-year>button{display:flex!important;align-items:center!important;gap:8px!important;min-height:46px!important;padding:9px 12px!important;border-left:4px solid var(--a,#31c9a5)!important;text-align:left!important}#spensus-news-v102 .ig-side .ig-year>button::before{content:"▸";display:inline-block!important;flex:0 0 11px!important;width:11px!important;color:#193b50!important;font-size:11px!important;font-weight:900!important;line-height:1!important;text-align:center!important}#spensus-news-v102 .ig-side .ig-year>button[aria-expanded="true"]::before{content:"▾"}#spensus-news-v102 .ig-side .ig-year>button>b{order:2!important;flex:1 1 auto!important;font-size:14px!important}#spensus-news-v102 .ig-side .ig-year>button>.ig-year-count{order:3!important;flex:0 0 auto!important}#spensus-news-v102 .ig-side .ig-year>button>.ig-year-arrow{display:none!important}#spensus-news-v102 .ig-side .ig-year-list[hidden]{display:none!important}@media(max-width:780px){#spensus-news-v102 .ig-side .ig-year>button{padding:9px 10px!important;gap:5px!important}#spensus-news-v102 .ig-side .ig-year>button>b{font-size:13px!important}}\`;document.head.appendChild(css)})();\n`;return new Response(source+patch,{status:response.status,statusText:response.statusText,headers:response.headers})}
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;
if(/^\/(?:sitemap(?:-[a-z0-9-]+)?\.(?:xml|txt)|robots\.txt)$/i.test(url.pathname)){event.respondWith(fetch(request,{cache:"no-store",redirect:"follow"}));return}
if(request.destination==="video"||request.destination==="audio"||request.headers.has("range"))return;
if(request.mode==="navigate"||request.destination==="document"){if(/^\/share(?:\/|$)|^\/share-v\d+(?:\/|$)/i.test(url.pathname)){event.respondWith(fetch(request,{cache:"no-store",redirect:"follow"}).catch(()=>Response.redirect("https://paibpsmart.github.io/",302)));return}if(url.pathname.endsWith("/editor-berita.html")||url.pathname.endsWith("/kendali-editor.html")){event.respondWith(networkFirst(request,700));return}event.respondWith(navigationInstant(event,request));return}
if(url.pathname.endsWith("/home-news-v102.js")){event.respondWith(newsRuntime(request));return}
if(url.pathname.endsWith("/news-ui-fast-v149.js")||url.pathname.endsWith("/share-ready-v152.js")||url.pathname.endsWith("/home-share-v133.js")||url.pathname.endsWith("/icon-art-v85.js")||url.pathname.endsWith("/service-worker.js")){event.respondWith(networkFirst(request,300));return}
if(request.destination==="style"||request.destination==="script"){event.respondWith(staleWhileRevalidate(event,request));return}if(request.destination==="image"||request.destination==="font"){event.respondWith(cacheFirst(request));return}event.respondWith(staleWhileRevalidate(event,request))});
