const CACHE_NAME="paibp-smart-v102-instagram-instant-r2";
const STATIC=[
  "./","./index.html","./logo-spensus.png","./gerbang.jpg","./assets/icons/icon-192.png",
  "./visual-v86.css?v=86","./icon-v86.css?v=86","./icon-art-v86.js?v=102","./visual-fix-v87.css?v=102","./visual-v89.css?v=102",
  "./home-clean-v92.js?v=102","./home-ticker-v94.css?v=102","./home-ticker-v93.js?v=102","./home-news-v102.js?v=102",
  "./reading-portal-v102.css?v=102","./reading-mobile-fix-v102.css?v=102","./artikel-portal-v102.js?v=102","./literasi-portal-v102.js?v=102","./literasi-seeds-v102.js?v=102","./artikel-extra-v102.js?v=102","./artikel-enrichment-v102.js?v=102","./artikel-topics-v102.js?v=102","./docx-lazy-v102.js?v=102","./artikel-data.js?v=37",
  "./teacher-preview-fix-v87.js?v=102","./owner-editor-v98.js?v=102","./multimapel-admin-v89.css?v=102","./multimapel-admin-v89.js?v=102",
  "./spensus-ai-v90.css?v=102","./spensus-ai-shell-v90.js?v=102","./news-editor-entry-v96.js?v=102","./news-editor-v99.css?v=102","./news-editor-chunked-v102.js?v=102"
];
self.addEventListener("install",event=>{self.skipWaiting();event.waitUntil(caches.open(CACHE_NAME).then(cache=>Promise.allSettled(STATIC.map(url=>cache.add(url)))))});
self.addEventListener("activate",event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key!==CACHE_NAME&&!key.startsWith("paibp-quran-kemenag-")).map(key=>caches.delete(key)));await self.clients.claim()})())});
async function networkFirst(request){const cache=await caches.open(CACHE_NAME);try{const response=await fetch(request,{cache:"no-store"});if(response&&response.ok)cache.put(request,response.clone());return response}catch{return await cache.match(request)||await cache.match(request,{ignoreSearch:true})||Response.error()}}
async function cacheFirst(request){const cache=await caches.open(CACHE_NAME);const hit=await cache.match(request)||await cache.match(request,{ignoreSearch:true});if(hit)return hit;try{const response=await fetch(request,{cache:"no-store"});if(response&&response.ok)cache.put(request,response.clone());return response}catch{return Response.error()}}
async function staleWhileRevalidate(request){const cache=await caches.open(CACHE_NAME);const hit=await cache.match(request)||await cache.match(request,{ignoreSearch:true});const update=fetch(request,{cache:"no-store"}).then(response=>{if(response&&response.ok)cache.put(request,response.clone());return response}).catch(()=>null);return hit||await update||Response.error()}
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==="navigate"||request.destination==="document"){event.respondWith(staleWhileRevalidate(request));return}if(url.pathname.endsWith('/icon-art-v85.js')||url.pathname.endsWith('/service-worker.js')){event.respondWith(networkFirst(request));return}const v=url.searchParams.get("v");if(v==="102"&&(request.destination==="script"||request.destination==="style")){event.respondWith(staleWhileRevalidate(request));return}if(["37","86","87","88","89","90","92","93","94","95","96","97","98","99","100","101"].includes(v)&&(request.destination==="script"||request.destination==="style")){event.respondWith(cacheFirst(request));return}if(request.destination==="image"||request.destination==="font"){event.respondWith(cacheFirst(request));return}event.respondWith(networkFirst(request))});